### ISSUE TITLE
@font-size tweeking / .to-rem mixin

### ISSUE THREAD

**Issue by FlexCarver** [cardinalcss/cardinalcss#82]
Hello!
I must be missing something. When I change the @font-size variable, the "rem" value remains the same?
For example setting it to 20 gives me
  /*px*/ font-size: 20px;
  /*rem*/ font-size: 1rem;
Why is it not 1.25rem ?

Also, changing the font-size variable changes the grid-item padding?
I solved it using the font-size classes, but what am I missing here?
Thank you for a reply.

**Comment by cbracco** [comment]
@FlexCarver good eye! The reason this is happening is because the `.to-rem()` mixin needs to be fed a base font size of 16 in order to do its calculations correctly. What I am going to do is hardcode the value 16 as the value for `@to-rem-font-size`, instead of inheriting the value of `@font-size`. This way you can override `@font-size` in your project and it should do the correct calculations.

**Comment by cbracco** [comment]
@FlexCarver this has been fixed as [3.5.0](https://github.com/cardinalcss/cardinalcss/releases/tag/3.5.0). Thanks again for pointing out the issue!
